# Generated by Django 3.2.3 on 2022-03-12 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='retrieving date')),
                ('filename', models.FileField(blank=True, null=True, upload_to='edoc/%Y/%m/')),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='Comment')),
            ],
        ),
    ]
